name: C CI

on:
  push:
    branches:
      - main
      - code-refactor
  pull_request:
    branches:
      - main
      - code-refactor

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y make gcc cppcheck clang-tidy

    - name: Run cppcheck
      run: make cppcheck

    - name: Run clang-tidy
      run: make clang-tidy

    - name: Run tests
      run: make test
